import React, { useEffect, useState } from 'react';
import DynaColorBox from './DynaColorBox';

// uses the color grid array generated by higher order components in order 
// to map DynaColorBox components to the DOM
function Grid(props) {

  let r = -1;
  let c = -1;

  return (
    <>
      {props.colorGrid.map((row) => {
      r++;
      return (
        <div className='row' key={r}>
          {row.map((box) => {
            {if (++c > (props.gridSize - 1)) {
              c = 0 
            }}
            return (
              <DynaColorBox
                clickVariance={props.clickVariance}
                key={`r${c}c${r}`}
                data-value={{r:r, c:c}}
                red={box.red}
                green={box.green}
                blue={box.blue}
                changeSurroundings={props.changeSurroundings}
                numColumns = {props.gridSize}
              />
            );
          })}
        </div>
      )
    })}
    </>
  )
}

export default Grid;